[package]
name = "aso"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.23.1"
tui = "0.18.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
textwrap = "0.16"
html2text = "0.4"